export const COLUNAS_KANBAN = [
  { id: 'os_nova', label: 'OS Nova', color: '#0EA5E9' },
  { id: 'diagnostico', label: 'Diagnóstico/Triagem', color: '#06B6D4' },
  { id: 'negociacao_em_andamento', label: 'Enviar Orçamento', color: '#F59E0B' },
  { id: 'aguardando_aprovacao', label: 'Aguardando Aprovação', color: '#F97316' },
  { id: 'orcamento_aprovado', label: 'Orçamento Aprovado', color: '#10B981' },
  { id: 'aguardando_peca', label: 'Aguardando Peça', color: '#8B5CF6' },
  { id: 'peca_em_transito', label: 'Peça em Trânsito', color: '#3B82F6' },
  { id: 'em_reparo_ci', label: 'Em Reparo CI', color: '#0EA5E9' },
  { id: 'rota_preta', label: 'Rota Preta', color: '#1a1a1a' },
  { id: 'rota_vermelha', label: 'Rota Vermelha', color: '#EF4444' },
  { id: 'rota_azul', label: 'Rota Azul', color: '#3B82F6' },
  { id: 'rota_verde', label: 'Rota Verde', color: '#10B981' },
  { id: 'rota_rosa', label: 'Rota Rosa', color: '#EC4899' },
  { id: 'rota_amarela', label: 'Rota Amarela', color: '#EAB308' },
  { id: 'rota_laranja', label: 'Rota Laranja', color: '#F97316' },
  { id: 'em_rota_ih', label: 'Agendado', color: '#10B981' },
  { id: 'instalacao_inicial', label: 'Instalação Inicial', color: '#7C3AED' },
  { id: 'service_handling', label: 'Service Handling', color: '#DB2777' },
  { id: 'return_handling', label: 'Return Handling', color: '#D97706' },
  { id: 'trade_up', label: 'Trade Up', color: '#0891B2' },
  { id: 'saw', label: 'SAW', color: '#14B8A6' },
  { id: 'controle_qualidade', label: 'Controle de Qualidade / OQC', color: '#2563EB' },
  { id: 'qa_bt', label: 'Q&A / BT', color: '#7C3AED' },
  { id: 'reparo_concluido', label: 'Reparo Concluído', color: '#10B981' },
  { id: 'aguardando_fechamento', label: 'Aguardando Fechamento', color: '#F59E0B' },
  { id: 'os_fechada', label: 'OS Fechada', color: '#6B7280' },
  { id: 'orcamentos_rejeitados', label: 'Orçamentos Rejeitados', color: '#EF4444' },
] as const;

export type ColunaKanban = typeof COLUNAS_KANBAN[number]['id'];
