[functions.manage-user]
verify_jwt = false

[functions.consultar-danfe]
verify_jwt = false

[functions.create-first-user]
verify_jwt = false

[functions.migrate-orphan-users]
verify_jwt = true

[functions.sync-gspn-attachments]
verify_jwt = true

[functions.sync-samsung-gspn]
verify_jwt = true

[functions.update-samsung-status]
verify_jwt = true

[functions.sync-existing-users]
verify_jwt = true

[functions.create-dev-user]
verify_jwt = true

[functions.ai-analysis]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.gia-chat]
verify_jwt = false

[functions.get-orcamento-publico]
verify_jwt = false

[functions.google-maps-proxy]
verify_jwt = true

[functions.evolution-webhook]
verify_jwt = false

[functions.emit-nfse]
verify_jwt = true

[functions.emit-nfe]
verify_jwt = false

[functions.sync-distribuicao-nfe]
verify_jwt = false

[functions.gia-send-relatorio]
verify_jwt = false

[functions.gia-relatorio-image]
verify_jwt = true

[functions.gia-relatorio]
verify_jwt = false

[functions.calculate-route-km]
verify_jwt = true

[functions.gia-alerta-2h]
verify_jwt = true

[functions.gspn-refresh-proxy]
verify_jwt = false

[functions.gspn-sync-status]
verify_jwt = false

[functions.whatsapp-meta-templates]
verify_jwt = false

[functions.whatsapp-24h-ping]
verify_jwt = false

[functions.gia-atendimento]
verify_jwt = false

[functions.gia-pipeline-notify]
verify_jwt = false
